pages:
    stage: deploy
    script:
        - echo 'Converting image files...'
        - find ./public/figure -name "*.png" | while read fname; do
        -   echo "$fname";
        -   convert $fname -strip -resize 1200x1200 -density 72x72 -units pixelsperinch $fname;
        - done
        - echo 'Done!'
        - rm -rf public/figure
    artifacts:
        paths:
            - public
    only:
        - master

